### ISSUE TITLE
[Feature Request] cusom iam role for the BashExecFunction

### ISSUE THREAD

**Issue by XuejiaoZhang** [pahud/cdk-lambda-bash#139]
In some cases, we need to run commands with specific role which has the permissions.
For example, when adding OIDC provider to EKS cluster, if SCP has some restriction (only a specified role is allowed to do the operation), we need to use the specified role to run command to add OIDC provider.

**Comment by pahud** [comment]
It makes sense to allow user to specify a custom iam role for the `BashExecFunction`. PR underway.

**Comment by pahud** [comment]
HI @XuejiaoZhang 

PR merged. Let me know if it works in your scenario.
