### ISSUE TITLE
User script should be aware of the current event type

### ISSUE THREAD

**Issue by pahud** [pahud/cdk-lambda-bash#30]
## Background

At this moment, the user script is not aware the event type(`onCreate`, `onUpdate` or `onDelete`) and not able to act accordingly:

https://github.com/pahud/cdk-lambda-bash/blob/e0d42062687ef8cefea130fe14f21cc93587606b/docker.d/function.sh#L26-L35

## Use Case

For example, we can create the `installArgoCD` like 

```ts
const installArgoCD = new BashExecFunction(...);

installArgoCD.run();
```

It's fine when we first deploy the CDK app, however, if we remove the `installArgoCD` lambda function resource, it's not going to `uninstall` ArgoCD as we expect.

The user script experience is probably like:

```sh
case ${CUSTOM_RESOURCE_EVENT_TYPE}  in
"create")
    install
;;
"delete")
    uninstall
;;
esac

funciton install() {
   kubectl apply -f  https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
}

funciton uninstall() {
   kubectl delete -f  https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
}
```

**Comment by pahud** [comment]
@guan840912 comments?

**Comment by guan840912** [comment]
yes, let's find it out 😁
